"""Contratos escritos à mão para dez templates conhecidos.

Servem de gabarito: é assim que o enriquecimento deve sair. Usados para testar
a busca vetorial de verdade, sem depender da API.
"""

OURO = {
    "drake_hotline_bling": {
        "funcao": "Contrastar duas opções, rejeitando a primeira e preferindo a segunda",
        "quando_usar": ["preferir uma coisa a outra", "trocar algo ruim por algo melhor",
                        "escolha óbvia entre duas alternativas", "antes e depois de aprender algo"],
        "tom": ["sarcástico", "leve"],
        "slots": [{"box_id": "text-0", "papel": "a opção rejeitada", "exemplo": "", "max_chars": 60},
                  {"box_id": "text-1", "papel": "a opção preferida", "exemplo": "", "max_chars": 60}],
        "nsfw": False,
    },
    "two_buttons": {
        "funcao": "Sofrer diante de um dilema entre duas opções difíceis de conciliar",
        "quando_usar": ["ter que escolher entre duas coisas que quer igualmente",
                        "dilema sem resposta boa", "adiar uma decisão difícil",
                        "querer duas coisas incompatíveis ao mesmo tempo"],
        "tom": ["ansioso", "autodepreciativo"],
        "slots": [{"box_id": "text-0", "papel": "a primeira opção do dilema", "exemplo": "", "max_chars": 40},
                  {"box_id": "text-1", "papel": "a segunda opção do dilema", "exemplo": "", "max_chars": 40},
                  {"box_id": "text-2", "papel": "quem enfrenta o dilema", "exemplo": "", "max_chars": 60}],
        "nsfw": False,
    },
    "distracted_boyfriend": {
        "funcao": "Ser tentado por algo novo e abandonar o que já funcionava bem",
        "quando_usar": ["largar o que funciona por novidade", "distrair-se com a moda do momento",
                        "trocar de ferramenta sem necessidade", "infidelidade a um compromisso"],
        "tom": ["irônico", "autodepreciativo"],
        "slots": [{"box_id": "text-0", "papel": "a novidade tentadora", "exemplo": "", "max_chars": 40},
                  {"box_id": "text-1", "papel": "quem se distrai", "exemplo": "", "max_chars": 30},
                  {"box_id": "text-2", "papel": "o que está sendo abandonado", "exemplo": "", "max_chars": 35}],
        "nsfw": False,
    },
    "disaster_girl": {
        "funcao": "Causar um desastre e observar satisfeito o resultado",
        "quando_usar": ["causar confusão de propósito", "sabotar algo e não se arrepender",
                        "provocar caos e assistir de longe"],
        "tom": ["malicioso", "triunfal"],
        "slots": [{"box_id": "text-0", "papel": "o desastre causado", "exemplo": "", "max_chars": 70},
                  {"box_id": "text-1", "papel": "quem causou e está satisfeito", "exemplo": "", "max_chars": 70}],
        "nsfw": False,
    },
    "waiting_skeleton": {
        "funcao": "Esperar por algo que demora tanto que já não vai acontecer",
        "quando_usar": ["esperar resposta que nunca chega", "aguardar promessa não cumprida",
                        "prazo que não acaba nunca", "fila ou processo eterno"],
        "tom": ["resignado", "sarcástico"],
        "slots": [{"box_id": "text-0", "papel": "quem espera", "exemplo": "", "max_chars": 60},
                  {"box_id": "text-1", "papel": "o que nunca chega", "exemplo": "", "max_chars": 60}],
        "nsfw": False,
    },
    "grus_plan": {
        "funcao": "Um plano que desanda na própria conclusão lógica, percebida tarde demais",
        "quando_usar": ["plano que se volta contra quem fez", "perceber a falha no fim",
                        "sequência de passos com final desastroso", "ideia boa que termina mal"],
        "tom": ["autodepreciativo", "absurdo"],
        "slots": [{"box_id": "text-0", "papel": "primeiro passo do plano", "exemplo": "", "max_chars": 45},
                  {"box_id": "text-1", "papel": "segundo passo do plano", "exemplo": "", "max_chars": 45},
                  {"box_id": "text-2", "papel": "a consequência indesejada", "exemplo": "", "max_chars": 45},
                  {"box_id": "text-3", "papel": "a mesma consequência, ao percebê-la", "exemplo": "", "max_chars": 45}],
        "nsfw": False,
    },
    "change_my_mind": {
        "funcao": "Declarar uma opinião polêmica e desafiar quem discorda",
        "quando_usar": ["afirmar algo controverso", "provocar debate",
                        "defender opinião impopular"],
        "tom": ["provocador", "confiante"],
        "slots": [{"box_id": "text-0", "papel": "a opinião polêmica", "exemplo": "", "max_chars": 70},
                  {"box_id": "text-1", "papel": "complemento da opinião", "exemplo": "", "max_chars": 70}],
        "nsfw": False,
    },
    "epic_handshake": {
        "funcao": "Duas coisas aparentemente diferentes que concordam num ponto em comum",
        "quando_usar": ["dois grupos opostos concordando", "encontrar terreno comum inesperado",
                        "coisas distintas com a mesma característica"],
        "tom": ["irônico", "triunfal"],
        "slots": [{"box_id": "text-0", "papel": "a primeira parte", "exemplo": "", "max_chars": 40},
                  {"box_id": "text-1", "papel": "a segunda parte", "exemplo": "", "max_chars": 40},
                  {"box_id": "text-2", "papel": "o que as duas têm em comum", "exemplo": "", "max_chars": 50}],
        "nsfw": False,
    },
    "uno_draw_25_cards": {
        "funcao": "Preferir aceitar um castigo grande a fazer algo simples que deveria fazer",
        "quando_usar": ["recusar-se a fazer o óbvio", "evitar uma tarefa a qualquer custo",
                        "teimosia diante de conselho sensato"],
        "tom": ["teimoso", "autodepreciativo"],
        "slots": [{"box_id": "text-0", "papel": "o que deveria fazer e recusa", "exemplo": "", "max_chars": 80},
                  {"box_id": "text-1", "papel": "quem recusa", "exemplo": "", "max_chars": 40}],
        "nsfw": False,
    },
    "sad_pablo_escobar": {
        "funcao": "Esperar sozinho, entediado, sem nada acontecer",
        "quando_usar": ["tédio", "esperar sem ter o que fazer", "solidão de fim de semana",
                        "aguardar algo sem previsão"],
        "tom": ["melancólico", "resignado"],
        "slots": [{"box_id": "text-0", "papel": "a situação de espera ou tédio", "exemplo": "", "max_chars": 60},
                  {"box_id": "text-1", "papel": "primeiro momento da espera", "exemplo": "", "max_chars": 35},
                  {"box_id": "text-2", "papel": "segundo momento, ainda esperando", "exemplo": "", "max_chars": 35}],
        "nsfw": False,
    },
}
